### ISSUE TITLE
New User Account - Requesting access to Data Tracker: David Bracken

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tracker#15]
Who: Steven Romero called me to let me know that new employee, **David Bracken** needs access to the Data Tracker as he will be adding work orders into the system. 
Division: Transportation Engineering

**Comment by jaime-mckeown** [comment]
@dianamartin do I add people to data tracker? Or do you want me to put his request for ArcGIS here as well?

**Comment by dianamartin** [comment]
@jaime-mckeown: I mean to assign you to a different issue...

**Comment by dianamartin** [comment]
Added David Bracken and emailed him instructions on logging in.
